title: Simon Kennedy # your name (or website title) here
logo: "/images/logo_sk.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate Diploma of Data Science (Applied), University of Adelaide 
  <br><br>
  Health practice owner for 17 years, Physiotherapist for 23 years. 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
